---
- hosts: localhost
  become: yes

  tasks:
  - name: update Kali packages
    apt:
      name: "*"
      state: latest

  - name: install list of packages
    apt:
      pkg:
        - powershell
        - terminator
        - keepassxc
...