---
- name: update Kali packages
  hosts: localhost
  connection: local
  become: yes
  apt:
    name: "*"
    state: latest

- name: install list of packages
  hosts: localhost
  connection: local
  become: yes
  apt:
    pkg:
      - powershell
      - terminator
      - keepassxc
...